### ISSUE TITLE
이메일 전달(Forwarding) 기능에서 원본 이메일에 첨부된 파일이름과 새롭게 첨부한 파일이름이 동일한 경우 예외가 발생한다.

### ISSUE THREAD

**Issue by logicielkr** [logicielkr/WebMUA#1]
1. 위치

메일목록 > 메일 조회 > 전달 > 저장

2. 상황

이메일 전달(Forwarding) 기능에서 원본 이메일에 첨부된 파일이름과 새롭게 첨부한 파일이름이 동일한 경우 예외가 발생한다.

3. 에러 메시지

kr.graha.sample.webmua.ForwardMailProcessorImpl.execute java.nio.file.FileAlreadyExistsException:
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:573)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
	at java.base/java.nio.file.Files.copy(Files.java:1294)
	at kr.graha.sample.webmua.ForwardMailProcessorImpl.execute(ForwardMailProcessorImpl.java:117)
	at kr.graha.post.model.Processor.execute(Processor.java:278)
	at kr.graha.post.model.QueryXMLImpl.executeProcessor(QueryXMLImpl.java:77)
	at kr.graha.post.model.QueryXMLImpl.document(QueryXMLImpl.java:534)
	at kr.graha.post.model.QueryXMLImpl.execute(QueryXMLImpl.java:616)
	at kr.graha.post.servlet.PostGeneratorServlet.execute(PostGeneratorServlet.java:99)
	at kr.graha.post.servlet.PostGeneratorServlet.doGet(PostGeneratorServlet.java:54)
	at kr.graha.post.servlet.PostGeneratorServlet.doPost(PostGeneratorServlet.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)

4. 원인

4.1. 직접적인 원인

이메일 전달(Forwarding) 기능에서 이메일을 저장할 때,
모든 처리가 완료된 후에,
원본 이메일에 첨부되어 있던 첨부파일을 복사한다.
(kr.graha.post.interfaces.Processor 를 구현한 kr.graha.sample.webmua.ForwardMailProcessorImpl 에서 처리)

이 때 파일이름이 중복되는지 검사하고, 그렇다면 (일련번호 따위를 붙이는 등의 방법으로) 처리해야 하는데, 이것이 누락되어서 발생하는 예외이다.

4.2. 간접적인 원인

이메일 전달(Forwarding) 화면에서 원본 이메일에 첨부되어 있던 파일목록이 표시되지 않기 때문에
사용자는 같은 파일을 다시 첨부할 가능성이 있다.

5. 해결방안

5.1. 원본 이메일에 첨부되어 있던 파일은 파일이름을 유지하고, 새롭게 업로드한 파일의 파일이름을 변경하는 방식으로 처리하는 방안이 있을 수 있다.

5.2. 이메일 전달(Forwarding) 화면에서 파일을 첨부하지 못하도록 막고, 원본 이메일에 첨부되어 있던 파일이 자동으로 첨부된다는 안내 메시지를 표시하는 방안도 있을 수 있다.
이메일 전달(Forwarding) 기능에서 새로운 파일을 첨부하는 것이 부적절하다는 것을 전제한 것이다.
사용자가 이메일을 저장 후에, 이메일 수정 화면에서 새로운 파일을 첨부할 수 있을 것이다.

5.3. 이메일 전달(Forwarding) 화면에서 원본 이메일에 첨부되어 있던 파일 목록을 표시하는 방안도 있을 수 있다.
다만, Graha 환경에서는 이메일을 Draft 폴더 등에 저장한 후에 원본 이메일에 첨부되어 있던 파일을 복사해야 하는데, 쓰레기 데이타가 쌓이는 문제가 발생할 수 있다.

**Comment by logicielkr** [comment]
1. 이메일 전달(Forwarding) 화면에서 css 로 첨부파일을 선택할 수 없도록 막았다.
2. 비정상적으로 첨부파일이 들어오는 상황을 대비하여, 500 에러가 발생하지 않도록, 파일을 복사할 때, 중복되는 파일이 있으면 일련번호를 붙여서 예외가 발생하지 않도록 수정했다.
